### ISSUE TITLE
Webview cannot load external JS/CSS content

### ISSUE THREAD

**Issue by saltfoundry** [skpm/sketch-module-web-view#77] opened 2018-12-02 12:01 UTC
When trying to pull reference externally hosted JS/CSS or use CSS imports that reference externally hosted content Sketch will crash.

As per Electron API, I have enabled unsecure content and disabled webSecurity in the web preferences but I don't believe these aspects are implemented in the module sketch-module-web-view api

`import BrowserWindow from 'sketch-module-web-view';

export default function() {
    
    const options = {
        identifier: 'unique.id',
        width: 1000, 
		height: 700,
		webPreferences: {
			webSecurity: false,
			allowRunningInsecureContent: true
		}
    };
   
	const browserWindow = new BrowserWindow(options);
	browserWindow.loadURL(require('./index.html'));
	
	browserWindow.once('ready-to-show', () => {
		browserWindow.show()
	})
}`

I can see in my network tab that the external resources are not loading. I've tried both Adobe typekit and a CDN of jQuery. 

Can anyone help?

**Comment by mathieudutour** [comment] 2018-12-03 16:39
Indeed there are not. We probably need to do that. I'll close this as it's a duplicate of #72

**Closed by mathieudutour** 2018-12-03 16:39 UTC
