### ISSUE TITLE
[help wanted] Unable to render Angular 4 app inside web view

### ISSUE THREAD

**Issue by kzxperience** [skpm/sketch-module-web-view#38] opened 2018-04-04 12:01 UTC
Hi,

first of all... much appreciation for your module!

Unfortunately, I having issues trying to render a web view created using Angular 4. I new to developing plugins for Sketch and I would like to display an SPA inside the web view.

Could you be so kind, to assist me on this topic?

Best regards

**Comment by mathieudutour** [comment] 2018-04-04 12:09
duplicate of https://github.com/skpm/with-webview/issues/11

**Closed by mathieudutour** 2018-04-04 12:09 UTC
